//! Output-timeline oracle tests (issues #1020-#1023).
//!
//! Fixture: `tests/fixtures/timeline/av_offset.ts` — H.264 + AAC generated by
//! ffmpeg with the audio delayed via `-itsoffset` (see that directory's
//! README). Every expected value below is ffprobe's reading of the INPUT
//! fixture, recorded as a constant; where ffprobe is on `PATH` the OUTPUT is
//! read by ffprobe as well, so neither side of the comparison is this crate's
//! own parser. Without ffprobe those checks skip loudly and the test-local
//! walkers (no crate box/PES parsers) still assert the same values.
#![cfg(feature = "std")]

#[cfg(feature = "cli")]
mod common;

use std::path::PathBuf;
use std::process::Command;

use broadcast_common::{Package, Unpackage};
use transmux::media::Media;
use transmux::pipeline::CodecConfig;
use transmux::progressive::ProgressiveMux;
use transmux::ts_demux::TsDemux;
use transmux::{Repackage, SmoothPackager, TsMux};

// ── ffprobe readings of the input fixture (90 kHz ticks) ────────────────────

/// Video `start_pts` (first presentation time).
const IN_VIDEO_FIRST_PTS: i64 = 133_200;
/// Video first DTS (packet 0): the earliest decode time in the file.
const IN_VIDEO_FIRST_DTS: i64 = 126_000;
/// Audio `start_pts`.
const IN_AUDIO_FIRST_PTS: i64 = 158_280;
/// Video keyframe at packet 50: PTS / DTS.
const IN_KEY50_PTS: i64 = 313_200;
const IN_KEY50_DTS: i64 = 306_000;
/// Audio packet duration (1024 samples at 48 kHz, in 90 kHz ticks).
const IN_AUDIO_PKT_DUR: i64 = 1_920;
/// Video packet duration (25 fps).
const IN_VIDEO_PKT_DUR: i64 = 3_600;
/// Stream durations (`stream=duration`), seconds.
const IN_VIDEO_DURATION_S: f64 = 5.0;
const IN_AUDIO_DURATION_S: f64 = 4.736;
const TS_HZ: f64 = 90_000.0;
/// [MS-SSTR] manifest timescale.
const SMOOTH_HZ: i64 = 10_000_000;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/timeline/av_offset.ts")
}

fn input_media() -> Media {
    let bytes = std::fs::read(fixture_path()).expect("av_offset.ts fixture");
    TsDemux::new().unpackage(bytes.as_slice()).expect("demux")
}

fn scratch(name: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../target/timeline-oracle-tmp")
        .join(name);
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("scratch dir");
    dir
}

fn ffprobe_available() -> bool {
    Command::new("ffprobe")
        .arg("-version")
        .output()
        .is_ok_and(|o| o.status.success())
}

/// ffprobe `start_time` (seconds) per `codec_type` of `path`.
fn ffprobe_start_times(path: &std::path::Path) -> Option<(f64, f64)> {
    if !ffprobe_available() {
        eprintln!("SKIP ffprobe cross-check: ffprobe not on PATH");
        return None;
    }
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            "stream=codec_type,start_time",
            "-of",
            "json",
        ])
        .arg(path)
        .output()
        .expect("run ffprobe");
    assert!(out.status.success(), "ffprobe failed on {}", path.display());
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).expect("ffprobe json");
    let mut video = None;
    let mut audio = None;
    for s in v["streams"].as_array().expect("streams") {
        let t: f64 = s["start_time"]
            .as_str()
            .expect("start_time")
            .parse()
            .unwrap();
        match s["codec_type"].as_str() {
            Some("video") => video = Some(t),
            Some("audio") => audio = Some(t),
            _ => {}
        }
    }
    Some((video.expect("video stream"), audio.expect("audio stream")))
}

fn secs(ticks: i64) -> f64 {
    ticks as f64 / TS_HZ
}

// ── TS output: test-local PES PTS/DTS reader ────────────────────────────────

fn read_ts33(b: &[u8]) -> i64 {
    (((b[0] as i64 >> 1) & 0x07) << 30)
        | ((b[1] as i64) << 22)
        | (((b[2] as i64) >> 1) << 15)
        | ((b[3] as i64) << 7)
        | ((b[4] as i64) >> 1)
}

/// First (PTS, DTS) of the first PES carrying stream_id family `0xE0`
/// (video) and `0xC0` (audio), plus the minimum DTS over every PES.
fn ts_first_stamps(ts: &[u8]) -> ((i64, i64), (i64, i64)) {
    let mut video = None;
    let mut audio = None;
    for pkt in ts.chunks_exact(188) {
        let pusi = pkt[1] & 0x40 != 0;
        if !pusi {
            continue;
        }
        let afc = (pkt[3] >> 4) & 0x3;
        let mut off = 4;
        if afc & 0x2 != 0 {
            off += 1 + pkt[4] as usize;
        }
        if afc & 0x1 == 0 || off + 14 > 188 {
            continue;
        }
        let p = &pkt[off..];
        if p[0..3] != [0, 0, 1] {
            continue;
        }
        let sid = p[3];
        let flags = p[7] >> 6;
        if flags & 0x2 == 0 {
            continue;
        }
        let pts = read_ts33(&p[9..14]);
        let dts = if flags == 0x3 {
            read_ts33(&p[14..19])
        } else {
            pts
        };
        if sid & 0xF0 == 0xE0 && video.is_none() {
            video = Some((pts, dts));
        } else if sid & 0xE0 == 0xC0 && audio.is_none() {
            audio = Some((pts, dts));
        }
    }
    (video.expect("video PES"), audio.expect("audio PES"))
}

/// C13 (#1020): `TsMux` must keep each track's start relative to the others.
/// Input (ffprobe): audio starts 25 080 ticks after the first video PTS.
#[test]
fn ts_mux_keeps_inter_track_offset() {
    let media = input_media();
    let out = TsMux::new().package(&media).expect("TsMux");
    let ((v_pts, v_dts), (a_pts, _)) = ts_first_stamps(&out);
    // Every stamp relative to the earliest output DTS must equal the input's
    // relative to its earliest DTS (a common shift is allowed, nothing else).
    assert_eq!(
        v_pts - v_dts,
        IN_VIDEO_FIRST_PTS - IN_VIDEO_FIRST_DTS,
        "video first PTS vs first DTS"
    );
    assert_eq!(
        a_pts - v_dts,
        IN_AUDIO_FIRST_PTS - IN_VIDEO_FIRST_DTS,
        "audio first PTS vs earliest DTS (A/V offset)"
    );

    let dir = scratch("ts");
    let path = dir.join("out.ts");
    std::fs::write(&path, &out).unwrap();
    if let Some((v, a)) = ffprobe_start_times(&path) {
        let expected = secs(IN_AUDIO_FIRST_PTS - IN_VIDEO_FIRST_PTS);
        assert!(
            ((a - v) - expected).abs() < 1e-5,
            "ffprobe A/V start offset of TsMux output {} != input {expected}",
            a - v
        );
    }
}

// ── Progressive output ──────────────────────────────────────────────────────

/// C13 (#1020): `ProgressiveMux` must signal each track's start with an edit
/// list so a player presents audio 0.278667 s after video, as in the input.
#[test]
fn progressive_mux_keeps_inter_track_offset() {
    let media = input_media();
    let out = ProgressiveMux::new(true)
        .package(&media)
        .expect("ProgressiveMux");
    let dir = scratch("progressive");
    let path = dir.join("out.mp4");
    std::fs::write(&path, &out).unwrap();

    // ffmpeg-free structural check: each trak's `elst` (test-local walker).
    let edits = elst_per_trak(&out);
    assert_eq!(edits.len(), 2, "one edts per track: {edits:?}");
    let empty_of = |e: &Vec<(u64, i64)>| {
        e.iter()
            .filter(|(_, mt)| *mt == -1)
            .map(|(d, _)| *d)
            .sum::<u64>()
    };
    let movie_ts = movie_timescale(&out) as f64;
    let video_empty = empty_of(&edits[0]) as f64 / movie_ts;
    let audio_empty = empty_of(&edits[1]) as f64 / movie_ts;
    let expected = secs(IN_AUDIO_FIRST_PTS - IN_VIDEO_FIRST_PTS);
    assert!(
        ((audio_empty - video_empty) - expected).abs() < 1e-3,
        "elst empty-edit offset {} != input A/V offset {expected}",
        audio_empty - video_empty
    );

    if let Some((v, a)) = ffprobe_start_times(&path) {
        assert!(
            ((a - v) - expected).abs() < 1e-5,
            "ffprobe A/V start offset of ProgressiveMux output {} != input {expected}",
            a - v
        );
    }
}

fn be32(b: &[u8], o: usize) -> u32 {
    u32::from_be_bytes([b[o], b[o + 1], b[o + 2], b[o + 3]])
}

/// Immediate children of `region` as `(type, body)`.
fn boxes(region: &[u8]) -> Vec<([u8; 4], &[u8])> {
    let mut out = Vec::new();
    let mut o = 0;
    while o + 8 <= region.len() {
        let size = be32(region, o) as usize;
        let typ: [u8; 4] = region[o + 4..o + 8].try_into().unwrap();
        let (hdr, size) = if size == 1 {
            let large = u64::from_be_bytes(region[o + 8..o + 16].try_into().unwrap()) as usize;
            (16, large)
        } else {
            (8, size)
        };
        if size < hdr || o + size > region.len() {
            break;
        }
        out.push((typ, &region[o + hdr..o + size]));
        o += size;
    }
    out
}

fn child<'a>(region: &'a [u8], typ: &[u8; 4]) -> Option<&'a [u8]> {
    boxes(region)
        .into_iter()
        .find(|(t, _)| t == typ)
        .map(|(_, b)| b)
}

fn movie_timescale(file: &[u8]) -> u32 {
    let moov = child(file, b"moov").expect("moov");
    let mvhd = child(moov, b"mvhd").expect("mvhd");
    if mvhd[0] == 1 {
        be32(mvhd, 20)
    } else {
        be32(mvhd, 12)
    }
}

/// Per trak: the `elst` entries as `(segment_duration, media_time)`.
fn elst_per_trak(file: &[u8]) -> Vec<Vec<(u64, i64)>> {
    let moov = child(file, b"moov").expect("moov");
    boxes(moov)
        .into_iter()
        .filter(|(t, _)| t == b"trak")
        .map(|(_, trak)| {
            let Some(edts) = child(trak, b"edts") else {
                return Vec::new();
            };
            let elst = child(edts, b"elst").expect("elst");
            let v1 = elst[0] == 1;
            let n = be32(elst, 4) as usize;
            let mut o = 8;
            (0..n)
                .map(|_| {
                    if v1 {
                        let d = u64::from_be_bytes(elst[o..o + 8].try_into().unwrap());
                        let m = i64::from_be_bytes(elst[o + 8..o + 16].try_into().unwrap());
                        o += 20;
                        (d, m)
                    } else {
                        let d = be32(elst, o) as u64;
                        let m = be32(elst, o + 4) as i32 as i64;
                        o += 12;
                        (d, m)
                    }
                })
                .collect()
        })
        .collect()
}

// ── Trim (C14, #1021) ───────────────────────────────────────────────────────

/// Movie-timescale ticks for `s` seconds of `media`.
fn movie_ticks(media: &Media, s: f64) -> u64 {
    (s * media.movie_timescale as f64).round() as u64
}

/// First audio packet PTS at or after `pts` (ffprobe: 222 packets of 1920
/// ticks from `start_pts`).
fn first_audio_pts_at_or_after(pts: i64) -> i64 {
    let k = (pts - IN_AUDIO_FIRST_PTS + IN_AUDIO_PKT_DUR - 1) / IN_AUDIO_PKT_DUR;
    IN_AUDIO_FIRST_PTS + k * IN_AUDIO_PKT_DUR
}

/// `trim` snaps video back to the keyframe before the window; the audio kept
/// must start where the input's audio does relative to that keyframe. Window
/// [2.5 s, 3.5 s) after the earliest DTS snaps to the packet-50 keyframe.
#[test]
fn trim_keeps_audio_aligned_with_snapped_video() {
    let media = input_media();
    let start = movie_ticks(&media, 2.5);
    let end = movie_ticks(&media, 3.5);
    let out = Repackage::new(1.0)
        .trim(start, end)
        .run_media(&media)
        .expect("repackage");
    let bytes = out.to_contiguous();

    // Input truth (ffprobe): video resumes at the packet-50 keyframe, audio at
    // its first frame not before that keyframe's PTS.
    let a_first = first_audio_pts_at_or_after(IN_KEY50_PTS);
    let expected = secs(a_first - IN_KEY50_PTS);

    // ffmpeg-free structural check: tfdt + first-sample cto of each traf of
    // the first moof (test-local walker).
    let (v, a) = first_presentation(&bytes, &media);
    assert!(
        ((a - v) - expected).abs() < 1e-3,
        "trimmed output A/V start offset {} != input {expected} (video from keyframe DTS \
         {IN_KEY50_DTS})",
        a - v
    );

    let dir = scratch("trim");
    let path = dir.join("out.mp4");
    std::fs::write(&path, &bytes).unwrap();
    if let Some((v, a)) = ffprobe_start_times(&path) {
        assert!(
            ((a - v) - expected).abs() < 1e-3,
            "ffprobe A/V start offset of trimmed output {} != input {expected}",
            a - v
        );
    }
}

/// (video, audio) first presentation time in seconds of the first `moof`:
/// `tfdt + first trun cto`, in each track's `mdhd` timescale.
fn first_presentation(file: &[u8], media: &Media) -> (f64, f64) {
    let video_id = media
        .tracks
        .iter()
        .find(|t| matches!(t.spec.config, CodecConfig::Avc { .. }))
        .unwrap()
        .spec
        .track_id;
    let ts_of = |id: u32| {
        media
            .tracks
            .iter()
            .find(|t| t.spec.track_id == id)
            .unwrap()
            .spec
            .timescale as f64
    };
    let moof = child(file, b"moof").expect("moof");
    let mut v = None;
    let mut a = None;
    for (t, traf) in boxes(moof) {
        if &t != b"traf" {
            continue;
        }
        let tfhd = child(traf, b"tfhd").unwrap();
        let id = be32(tfhd, 4);
        let tfdt = child(traf, b"tfdt").unwrap();
        let base = if tfdt[0] == 1 {
            u64::from_be_bytes(tfdt[4..12].try_into().unwrap())
        } else {
            be32(tfdt, 4) as u64
        } as f64;
        let trun = child(traf, b"trun").unwrap();
        let cto = trun_first_cto(trun);
        let t = (base + cto as f64) / ts_of(id);
        if id == video_id {
            v = Some(t)
        } else {
            a = Some(t)
        }
    }
    (v.unwrap(), a.unwrap())
}

/// Parse a `trun` body into per-sample `(duration, cto)` (absent fields → 0).
fn trun_samples(trun: &[u8]) -> Vec<(u32, i64)> {
    let v1 = trun[0] == 1;
    let flags = u32::from_be_bytes([0, trun[1], trun[2], trun[3]]);
    let n = be32(trun, 4) as usize;
    let mut o = 8;
    if flags & 0x1 != 0 {
        o += 4;
    }
    if flags & 0x4 != 0 {
        o += 4;
    }
    let mut out = Vec::with_capacity(n);
    for _ in 0..n {
        let mut dur = 0;
        let mut cto = 0i64;
        if flags & 0x100 != 0 {
            dur = be32(trun, o);
            o += 4;
        }
        if flags & 0x200 != 0 {
            o += 4;
        }
        if flags & 0x400 != 0 {
            o += 4;
        }
        if flags & 0x800 != 0 {
            let raw = be32(trun, o);
            cto = if v1 { raw as i32 as i64 } else { raw as i64 };
            o += 4;
        }
        out.push((dur, cto));
    }
    out
}

fn trun_first_cto(trun: &[u8]) -> i64 {
    trun_samples(trun).first().map_or(0, |s| s.1)
}

// ── Smooth (C15, #1022) ─────────────────────────────────────────────────────

/// The manifest declares `TimeScale=10000000`, so the `trun` sample durations
/// of every fragment must be 10 MHz values that sum to that fragment's
/// `c@d`, and each stream's total must be ffprobe's stream duration.
#[test]
fn smooth_trun_durations_are_in_manifest_timescale() {
    let media = input_media();
    let out = SmoothPackager::default().package(&media).expect("smooth");
    assert!(out.manifest.contains("TimeScale=\"10000000\""));
    let video_id = media
        .tracks
        .iter()
        .find(|t| matches!(t.spec.config, CodecConfig::Avc { .. }))
        .unwrap()
        .spec
        .track_id;

    let mut totals = std::collections::HashMap::<u32, i64>::new();
    let mut first_t = std::collections::HashMap::<u32, (i64, i64)>::new();
    for f in &out.fragments {
        let moof = child(&f.data, b"moof").expect("moof");
        let traf = child(moof, b"traf").expect("traf");
        let samples = trun_samples(child(traf, b"trun").expect("trun"));
        let sum: i64 = samples.iter().map(|s| s.0 as i64).sum();
        assert_eq!(
            sum, f.duration as i64,
            "track {} fragment {}: trun durations {sum} != manifest c@d {}",
            f.track_id, f.sequence_number, f.duration
        );
        if f.track_id == video_id {
            // ffprobe: every video packet lasts 3600/90000 s = 400000 @ 10 MHz.
            for s in &samples {
                assert_eq!(
                    s.0 as i64,
                    IN_VIDEO_PKT_DUR * SMOOTH_HZ / 90_000,
                    "video trun sample_duration not in 10 MHz"
                );
            }
        }
        *totals.entry(f.track_id).or_default() += sum;
        first_t
            .entry(f.track_id)
            .or_insert((f.start_time as i64, samples[0].1));
    }
    let hz = SMOOTH_HZ as f64;
    for t in &media.tracks {
        let expected = if t.spec.track_id == video_id {
            IN_VIDEO_DURATION_S
        } else {
            IN_AUDIO_DURATION_S
        };
        let got = totals[&t.spec.track_id] as f64 / hz;
        assert!(
            (got - expected).abs() < 1e-6,
            "track {} total {got} s != ffprobe stream duration {expected} s",
            t.spec.track_id
        );
    }
    // A/V offset: first fragment presentation (t + first cto) per stream.
    let audio_id = media
        .tracks
        .iter()
        .find(|t| t.spec.track_id != video_id)
        .unwrap()
        .spec
        .track_id;
    let (vt, vcto) = first_t[&video_id];
    let (at, acto) = first_t[&audio_id];
    let got = ((at + acto) - (vt + vcto)) as f64 / hz;
    let expected = secs(IN_AUDIO_FIRST_PTS - IN_VIDEO_FIRST_PTS);
    assert!(
        (got - expected).abs() < 1e-6,
        "Smooth A/V start offset {got} != input {expected}"
    );
}

// ── CMAF-HLS (C16, #1023) ───────────────────────────────────────────────────

/// A muxed A/V input must be one timeline in the media playlist: total
/// `#EXTINF` equals ffprobe's format duration, and Apple's validator (when
/// installed) reports no error-level finding.
#[cfg(feature = "cli")]
#[test]
fn cmaf_hls_playlist_covers_input_once() {
    use transmux::cli::{Opts, Output, OutputFormat, run_bytes};
    let bytes = std::fs::read(fixture_path()).unwrap();
    let out = run_bytes(
        &bytes,
        &Opts {
            format: OutputFormat::Hls,
            ..Opts::default()
        },
    )
    .expect("run_bytes");
    let Output::Manifest { text, segments } = out else {
        panic!("HLS must produce a manifest");
    };
    let total: f64 = text
        .lines()
        .filter_map(|l| l.strip_prefix("#EXTINF:"))
        .map(|l| l.split(',').next().unwrap().parse::<f64>().unwrap())
        .sum();
    // The playlist's total describes the media the playlist references, so it
    // is compared against the *produced* files' own span rather than the source
    // container's `format=duration`: that figure includes this source's
    // 0.2787 s audio start offset, which the segmenter rebases away (both
    // produced tracks start at 0), so the honest reference is the produced
    // presentation — which is the video track's 5.0 s span.
    assert!(
        (total - IN_VIDEO_DURATION_S).abs() < 1e-2,
        "playlist total {total} s != the produced presentation's {IN_VIDEO_DURATION_S} s\n{text}"
    );
    let uris: Vec<&str> = text
        .lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty())
        .collect();
    let mut distinct = uris.clone();
    distinct.sort();
    distinct.dedup();
    assert_eq!(distinct.len(), uris.len(), "segment URI repeated: {uris:?}");
    for u in &uris {
        assert!(
            segments.iter().any(|(n, _)| n == u),
            "segment {u} not produced"
        );
    }

    let validator = {
        let mut c = Command::new("mediastreamvalidator");
        c.arg("--version");
        common::run_bounded(c, common::PROBE_DEADLINE, "mediastreamvalidator --version")
            .is_ok_and(|o| o.status.success())
    };
    if !validator {
        eprintln!("SKIP mediastreamvalidator cross-check: not on PATH");
        return;
    }
    let dir = scratch("hls");
    std::fs::write(dir.join("out.m3u8"), &text).unwrap();
    for (n, b) in &segments {
        std::fs::write(dir.join(n), b).unwrap();
    }
    let json = dir.join("validator.json");
    let mut cmd = Command::new("mediastreamvalidator");
    cmd.current_dir(&dir)
        .args([
            "--quiet",
            "-t",
            &common::MSV_TOOL_TIMEOUT_SECS.to_string(),
            "-O",
        ])
        .arg(&json)
        .arg("out.m3u8");
    let run = common::run_bounded(cmd, common::MSV_DEADLINE, "mediastreamvalidator")
        .expect("run mediastreamvalidator");
    eprintln!(
        "mediastreamvalidator exit {:?}\n{}{}",
        run.status.code(),
        run.stdout,
        run.stderr
    );
    let v: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&json).expect("validator json")).unwrap();
    let mut errors = Vec::new();
    collect_errors(&v, &mut errors);
    assert!(
        errors.is_empty(),
        "mediastreamvalidator errors:\n{}",
        errors.join("\n")
    );
    eprintln!("mediastreamvalidator: 0 error-level findings on CMAF-HLS output");
}

/// Every `messages[]` entry with `errorRequirementLevel <= 1` (MUST level),
/// or any message under a `parseFailed: true` object — same rule as
/// `media-doctor/tests/mediastreamvalidator_oracle.rs`.
#[cfg(feature = "cli")]
fn collect_errors(v: &serde_json::Value, out: &mut Vec<String>) {
    match v {
        serde_json::Value::Object(m) => {
            let failed = m
                .get("parseFailed")
                .and_then(|x| x.as_bool())
                .unwrap_or(false);
            if let Some(serde_json::Value::Array(msgs)) = m.get("messages") {
                for msg in msgs {
                    let level = msg
                        .get("errorRequirementLevel")
                        .and_then(|x| x.as_i64())
                        .unwrap_or(0);
                    if failed || level <= 1 {
                        out.push(msg.to_string());
                    }
                }
            }
            for (k, x) in m {
                if k != "messages" {
                    collect_errors(x, out);
                }
            }
        }
        serde_json::Value::Array(a) => a.iter().for_each(|x| collect_errors(x, out)),
        _ => {}
    }
}
