//! Independent-tool oracle for issue #1041 (Teletext bit reversal).
//!
//! `webvtt_teletext_fixture.rs`'s oracle is this project's own reading of EN
//! 300 706 (the bit-reversal argument in that test's module docs), and its
//! fixture bytes are hand-generated by this crate's own verified encoders --
//! so a mistake shared by the generator and the decoder would go unnoticed.
//! This test instead decodes a **committed real MPEG-2 TS** (PAT + PMT with a
//! `teletext_descriptor` + PES-carried Teletext, built exactly like a real
//! DVB Teletext subtitle service) through **TSDuck 3.44's own independent
//! Teletext demux** (`tsp -P teletext`, which implements EN 300 472/706 from
//! scratch, including its own `REVERSE_8` bit-reversal table -- see
//! `fixtures/teletext/README.md` for the exact commands) and asserts this
//! crate's decode of the *same* TS bytes agrees.
//!
//! ## Two documented, deliberate differences from TSDuck's own output
//!
//! - **Text only, not timing.** TSDuck's `showTimestamp`/`hideTimestamp` are
//!   derived from its own `pidDuration()` PTS-tracking, which samples the
//!   *previously* tracked PTS at the point a page header is processed (PTS
//!   tracking updates only after `PESDemux::feedPacket` returns -- see
//!   `TimeTrackerDemux::feedPacket`), not the header's own PTS. That is a
//!   different, TSDuck-internal timing model from this crate's `MediaTime`
//!   (which is exactly the fed `pts_90k`), so times are not asserted here.
//! - **A single leading space per line.** The fixture's two subtitle rows are
//!   wrapped in EN 300 706's Start Box (`0x0B`)/End Box (`0x0A`) spacing
//!   attributes (clause 12.2), the real-world convention that marks which
//!   part of a Level-1 Teletext page is boxed subtitle text. TSDuck's SRT
//!   extraction specifically looks for this box pair and **excludes** the
//!   marker characters from the extracted line
//!   (`tsTeletextDemux.cpp::processTeletextPage`, `colStart`/`colStop`). This
//!   crate's Teletext decoder does not implement boxed-subtitle detection
//!   (documented gap, `webvtt::teletext` module docs: "no styling"); it
//!   treats every spacing-attribute control code `< 0x20`, Start/End Box
//!   included, as a literal space (`latin_g0_char`). The Start Box therefore
//!   survives as a single leading space (the End Box's trailing space is
//!   absorbed by `trim_end`). Stripped explicitly below, with this comment
//!   as the record of why.
#![cfg(feature = "teletext")]

use broadcast_common::Unpackage;
use dvb_vbi::TeletextDataField;
use std::fs;
use std::path::{Path, PathBuf};
use timed_metadata::webvtt::TeletextCueExtractor;
use transmux::{CodecConfig, TsDemux};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("fixtures")
        .join("teletext")
}

/// Teletext PID declared in the fixture's PMT (`teletext_descriptor`, tag
/// `0x56`, `teletext_type` `0x02` subtitle page, magazine 8 / page `0x88`).
const TELETEXT_PID: u16 = 0x0101;

/// Walk one PES payload's `PES_data_field` (EN 300 472 §4.3: `data_identifier`
/// plus one or more `data_unit()`s) and return every 44-byte Teletext wire
/// field (`data_unit_id` `0x02`/`0x03`, `data_unit_length` `0x2C`).
fn teletext_wire_fields(pes_payload: &[u8]) -> Vec<[u8; 44]> {
    let mut out = Vec::new();
    let Some((&data_identifier, mut rest)) = pes_payload.split_first() else {
        return out;
    };
    if !(0x10..=0x1F).contains(&data_identifier) {
        return out;
    }
    while rest.len() >= 2 {
        let unit_id = rest[0];
        let unit_len = rest[1] as usize;
        rest = &rest[2..];
        if unit_len > rest.len() {
            break;
        }
        if unit_len == 44 && matches!(unit_id, 0x02 | 0x03) {
            let mut field = [0u8; 44];
            field.copy_from_slice(&rest[..44]);
            out.push(field);
        }
        rest = &rest[unit_len..];
    }
    out
}

/// Demux the committed real TS through `transmux::TsDemux` (independent of
/// the hand-written frame list `webvtt_teletext_fixture.rs` uses) and decode
/// every Teletext frame on [`TELETEXT_PID`] through this crate's own
/// extractor.
fn decode_via_this_crate(ts_bytes: &[u8]) -> Vec<timed_metadata::webvtt::Cue> {
    let media = TsDemux::new()
        .unpackage(ts_bytes)
        .expect("demux the committed Teletext TS fixture");
    let track = media
        .tracks
        .iter()
        .find(|t| {
            t.spec.source_pid == Some(TELETEXT_PID)
                && matches!(t.config(), CodecConfig::Data { .. })
        })
        .expect("fixture must contain an opaque Data track on the Teletext PID");

    let mut ex = TeletextCueExtractor::new(8, 0x88);
    let mut last_pts = 0u64;
    for sample in &track.samples {
        let pts = sample
            .pts
            .expect("every demuxed Teletext PES sample carries a PTS")
            .max(0) as u64;
        last_pts = pts;
        let fields: Vec<TeletextDataField> = teletext_wire_fields(&sample.data)
            .into_iter()
            .map(|w| TeletextDataField::parse(&w).expect("valid 44-byte Teletext wire field"))
            .collect();
        ex.push_frame(pts, &fields);
    }
    ex.finalize(last_pts + 1);
    ex.into_cues()
}

/// Extract the text lines of the SRT's one (and only) entry -- everything
/// after the index + timecode lines, up to the trailing blank line.
fn oracle_srt_text_lines(srt: &str) -> Vec<&str> {
    srt.lines()
        .skip(2) // index line, timecode line
        .take_while(|l| !l.trim().is_empty())
        .collect()
}

#[test]
fn matches_tsduck_teletext_plugin_oracle() {
    let ts_bytes = fs::read(fixtures_dir().join("teletext_subtitle_boxed.ts"))
        .expect("read committed TSDuck-oracle Teletext TS fixture");
    let oracle_srt =
        fs::read_to_string(fixtures_dir().join("teletext_subtitle_boxed.tsduck-oracle.srt"))
            .expect("read committed tsp -P teletext oracle SRT");

    let cues = decode_via_this_crate(&ts_bytes);
    assert!(!cues.is_empty(), "expected at least one cue: {cues:?}");
    // TSDuck flushes one frame per page (on the next header for the same
    // page), while this crate's diff-based extractor emits one cue per
    // display change (module docs: "progressive reveal" granularity) -- so
    // compare against the *final* cue (the complete two-row display just
    // before the closing/erase header), not a 1:1 cue count.
    let final_cue_text = &cues.last().unwrap().text;

    // Strip the single leading space each line inherits from the Start Box
    // marker (see module doc above); TSDuck excludes the marker entirely.
    let got: Vec<&str> = final_cue_text
        .lines()
        .map(|l| l.strip_prefix(' ').unwrap_or(l))
        .collect();
    let want = oracle_srt_text_lines(&oracle_srt);
    assert_eq!(
        got, want,
        "this crate's decode must match TSDuck's independent Teletext demux \
         (fixtures/teletext/teletext_subtitle_boxed.tsduck-oracle.srt)"
    );
}
