//! Fixture tests for `check_hls_playlist` — HLS playlist validation using
//! structured model (broadcast_hls::MediaPlaylist::parse) plus line-based checks.
//!
//! Fixtures live in `fixtures/hls/`:
//! - `valid.m3u8` — well-formed playlist → zero findings.
//! - `missing-extm3u.m3u8` — missing `#EXTM3U` header.
//! - `bad-extinf.m3u8` — EXTINF 15.0 vs TARGETDURATION 10.
//! - `malformed-daterange.m3u8` — DATERANGE missing required `ID` attribute.
//! - `reference-vod.m3u8` — 10-segment VOD playlist generated by broadcast_hls::MediaPlaylist::to_m3u8().

use std::fs;

use media_doctor::{Report, check_hls_playlist};

fn read_fixture(name: &str) -> String {
    let path = format!("{}/../fixtures/hls/{}", env!("CARGO_MANIFEST_DIR"), name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read fixture {path}: {e}"))
}

fn findings<'a>(report: &'a Report, rule_id: &str) -> Vec<&'a media_doctor::Finding> {
    report
        .findings()
        .iter()
        .filter(|f| f.rule_id == rule_id)
        .collect()
}

// -------------------------------------------------------------------------
// Clean manifest — zero findings
// -------------------------------------------------------------------------

/// `valid.m3u8` — well-formed media playlist → ZERO findings.
#[test]
fn valid_fixture_clean() {
    let text = read_fixture("valid.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);

    assert!(
        report.is_empty(),
        "valid playlist should produce no findings, got {}: {:?}",
        report.len(),
        report.findings(),
    );
}

/// `reference-vod.m3u8` — a real VOD playlist generated by this workspace's
/// own `broadcast_hls::MediaPlaylist::to_m3u8()` (10 segments, 10s TARGETDURATION,
/// ENDLIST). Must produce zero findings.
#[test]
fn reference_vod_playlist_clean() {
    let text = read_fixture("reference-vod.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);
    assert!(
        report.is_empty(),
        "reference VOD playlist should have no findings, got {}: {:?}",
        report.len(),
        report.findings(),
    );
}

// -------------------------------------------------------------------------
// Positive tests — violations are detected
// -------------------------------------------------------------------------

/// Missing `#EXTM3U` header → `hls-missing-extm3u` finding.
#[test]
fn missing_extm3u_detected() {
    let text = read_fixture("missing-extm3u.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);

    let hits = findings(&report, "hls-missing-extm3u");
    assert!(
        !hits.is_empty(),
        "missing-extm3u fixture should produce hls-missing-extm3u, got {:?}",
        report.findings(),
    );
}

/// EXTINF 15.0 > TARGETDURATION 10 → `hls-extinf-exceeds-target` finding.
#[test]
fn extinf_exceeds_target_detected() {
    let text = read_fixture("bad-extinf.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);

    let hits = findings(&report, "hls-extinf-exceeds-target");
    assert!(
        !hits.is_empty(),
        "bad-extinf should produce hls-extinf-exceeds-target, got {:?}",
        report.findings(),
    );
}

/// Malformed DATERANGE → `hls-malformed-daterange` finding.
#[test]
fn malformed_daterange_detected() {
    let text = read_fixture("malformed-daterange.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);

    let hits = findings(&report, "hls-malformed-daterange");
    assert!(
        !hits.is_empty(),
        "malformed-daterange should produce hls-malformed-daterange, got {:?}",
        report.findings(),
    );
}

// -------------------------------------------------------------------------
// LL-HLS structured-model tests
// -------------------------------------------------------------------------

/// A playlist with both ENDLIST and PRELOAD-HINT → `hls-preload-hint-with-endlist`.
#[test]
fn preload_hint_with_endlist_detected() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PRELOAD-HINT:TYPE=PART,URI=\"next-part.m4s\"
#EXTINF:4.0,
seg0.m4s
#EXT-X-ENDLIST
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-preload-hint-with-endlist");
    assert!(
        !hits.is_empty(),
        "preload-hint+endlist should produce finding, got {:?}",
        report.findings(),
    );
}

/// A playlist with EXT-X-SKIP but no CAN-SKIP-UNTIL → `hls-skip-without-can-skip-until`.
#[test]
fn skip_without_can_skip_until_detected() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:100
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-SKIP:SKIPPED-SEGMENTS=96
#EXTINF:4.0,
seg100.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-skip-without-can-skip-until");
    assert!(
        !hits.is_empty(),
        "skip without CAN-SKIP-UNTIL should produce finding, got {:?}",
        report.findings(),
    );
}

/// A playlist with a part whose duration is below 85% of PART-TARGET.
#[test]
fn part_duration_too_short_detected() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        !hits.is_empty(),
        "too-short part duration should produce finding, got {:?}",
        report.findings(),
    );
    assert!(
        hits.iter()
            .any(|f| f.severity == media_doctor::Severity::Error),
        "too-short part duration must be Error severity, not Warning"
    );
}

/// A part below 85% duration floor with `INDEPENDENT=YES` is ACCEPTED
/// (RFC 8216bis §4.4.4.9 exception).
#[test]
fn short_part_with_independent_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\",INDEPENDENT=YES
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        hits.is_empty(),
        "INDEPENDENT=YES part below 85% floor must be accepted, got {:?}",
        report.findings(),
    );
}

/// A part below 85% duration floor with `GAP=YES` is ACCEPTED
/// (RFC 8216bis §4.4.4.9 exception).
#[test]
fn short_part_with_gap_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\",GAP=YES
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        hits.is_empty(),
        "GAP=YES part below 85% floor must be accepted, got {:?}",
        report.findings(),
    );
}

/// A part below 85% duration floor IMMEDIATELY BEFORE a `GAP=YES` part is
/// ACCEPTED (RFC 8216bis §4.4.4.9 exception).
#[test]
fn short_part_before_gap_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\",GAP=YES
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        hits.is_empty(),
        "part before GAP=YES below 85% floor must be accepted, got {:?}",
        report.findings(),
    );
}

/// The FINAL part of a segment below 85% duration floor is ACCEPTED
/// (RFC 8216bis §4.4.4.9 exception).
#[test]
fn short_final_part_of_segment_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.333,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.100,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        hits.is_empty(),
        "final part of segment below 85% floor must be accepted, got {:?}",
        report.findings(),
    );
}

// -------------------------------------------------------------------------
// §4.4.4.9 upper bound and the open segment (issue #1112, audit MD-W2)
// -------------------------------------------------------------------------

/// An `INDEPENDENT=YES` part LONGER than PART-TARGET must still be flagged:
/// the exception list relaxes only the 85% floor, not "MUST be less than or
/// equal to the Part Target Duration" (RFC 8216bis §4.4.4.9).
#[test]
fn part_over_target_with_independent_still_flagged() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.500,URI=\"part0.m4s\",INDEPENDENT=YES
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert_eq!(
        hits.len(),
        1,
        "an INDEPENDENT part of 0.500s exceeds PART-TARGET 0.333s and must be \
         flagged (the exemption covers the 85% floor only), got {:?}",
        report.findings(),
    );
    assert!(
        hits[0].message.contains("0.5") && hits[0].message.contains("PART-TARGET"),
        "the finding must state the upper bound it violated, got {:?}",
        hits[0].message,
    );
}

/// The FINAL part of a parent segment longer than PART-TARGET must also be
/// flagged — same reasoning as INDEPENDENT above.
#[test]
fn part_over_target_final_of_segment_still_flagged() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.333,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.700,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert_eq!(
        hits.len(),
        1,
        "the final part of a segment is exempt from the 85% floor, not from \
         the PART-TARGET ceiling; got {:?}",
        report.findings(),
    );
}

/// The open (in-progress) segment's parts are the live edge — the most
/// important ones to check. A part over PART-TARGET there must be flagged.
#[test]
fn open_segment_part_over_target_flagged() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.333,URI=\"part0.m4s\"
#EXTINF:1.0,
seg0.m4s
#EXT-X-PART:DURATION=0.333,URI=\"open0.m4s\"
#EXT-X-PART:DURATION=0.900,URI=\"open1.m4s\"
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert_eq!(
        hits.len(),
        1,
        "a 0.900s part in the open segment exceeds PART-TARGET 0.333s and must \
         be flagged; got {:?}",
        report.findings(),
    );
}

/// A closed-segment part and an open-segment part both below the 85% floor
/// must each be flagged (the open segment is not skipped).
#[test]
fn open_segment_part_below_floor_flagged() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
#EXT-X-PART:DURATION=0.050,URI=\"open0.m4s\"
#EXT-X-PART:DURATION=0.333,URI=\"open1.m4s\"
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert_eq!(
        hits.len(),
        2,
        "both the 0.100s closed-segment part and the 0.050s open-segment part \
         are below the 85% floor and must be flagged; got {:?}",
        report.findings(),
    );
}

// -------------------------------------------------------------------------
// Parse-error reporting and media/master classification (issue #1112, MD-W11)
// -------------------------------------------------------------------------

/// A Media Playlist that should not parse must be reported *as a Media
/// Playlist*, with the parser's own reason in the finding — never silently
/// routed to the (rule-less) multivariant branch, which reported clean.
#[test]
fn unparseable_media_playlist_is_reported_with_the_parser_reason() {
    // `#EXTINF` marks this as a Media Playlist (§4.4.4.1), but a segment URI
    // line is missing and there is no `#EXT-X-TARGETDURATION`.
    let text = "\
#EXTM3U
#EXTINF:10.0,
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let parse_errors = findings(&report, "hls-parse-error");
    assert_eq!(
        parse_errors.len(),
        1,
        "a Media Playlist that fails its media parse must be reported; got {:?}",
        report.findings(),
    );
    assert!(
        parse_errors[0].message.contains("Media Playlist"),
        "the finding must say which kind failed to parse, got {:?}",
        parse_errors[0].message,
    );
    assert!(
        parse_errors[0].message.len()
            > "Playlist failed to parse as a valid Media Playlist: ".len(),
        "the parser's own reason must be included, got {:?}",
        parse_errors[0].message,
    );
}

/// A Multivariant Playlist whose `#EXT-X-STREAM-INF` is malformed is reported
/// as a *Multivariant* parse failure, not as a Media one.
#[test]
fn malformed_master_playlist_is_reported_as_multivariant() {
    // `#EXT-X-STREAM-INF` with no attributes at all.
    let text = "\
#EXTM3U
#EXT-X-STREAM-INF:
variant.m3u8
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let parse_errors = findings(&report, "hls-parse-error");
    assert_eq!(
        parse_errors.len(),
        1,
        "a malformed Multivariant Playlist must be reported; got {:?}",
        report.findings(),
    );
    assert!(
        parse_errors[0].message.contains("Multivariant"),
        "the finding must name the Multivariant kind, got {:?}",
        parse_errors[0].message,
    );
}

/// A playlist with Media-Playlist tags is never validated as a Multivariant
/// Playlist, and vice versa — the classification is by tag, not by which
/// parse happens to succeed.
#[test]
fn media_tags_route_to_media_rules() {
    // Well-formed Media Playlist: must produce no parse error.
    let text = "\
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.0,
seg0.ts
#EXT-X-ENDLIST
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);
    assert!(
        findings(&report, "hls-parse-error").is_empty(),
        "a well-formed Media Playlist must not report a parse error; got {:?}",
        report.findings(),
    );
}

/// A playlist carrying neither a Media nor a Multivariant signature tag must
/// not be reported clean just because one parser accepts it (audit MD-W11).
#[test]
fn playlist_with_no_signature_tag_is_reported() {
    // `#EXT-X-ENDLIST`/`EXT-X-MEDIA-SEQUENCE` are Media Metadata / Media
    // Segment-adjacent tags but neither identifies the playlist as a Media
    // Playlist (§4.4.3.1 requires TARGETDURATION; §4.4.4.1 EXTINF).
    let text = "\
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ENDLIST
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);
    let hits = findings(&report, "hls-unsupported-playlist");
    assert_eq!(
        hits.len(),
        1,
        "a playlist with no Media/Multivariant signature tag must be reported, \
         not validated as clean; got {:?}",
        report.findings(),
    );
}

/// A part duration within 1 ms of the 85% floor is accepted: the bounds come
/// from decimal text with three fractional digits, so an exactly-at-the-bound
/// duration can land one ULP the wrong way. 0.283 s is 50 µs below
/// PART-TARGET 0.333 s's 85% floor (0.28305 s) — inside the tolerance, and a
/// real violation is orders of magnitude larger.
#[test]
fn part_duration_within_epsilon_of_the_floor_is_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.333,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.283,URI=\"part1.m4s\"
#EXT-X-PART:DURATION=0.333,URI=\"part2.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);
    assert!(
        findings(&report, "hls-part-duration-range").is_empty(),
        "0.283 is 50 µs below the 0.28305 floor, inside the 1 ms tolerance; \
         got {:?}",
        report.findings(),
    );
}
