//! Fixture tests for `check_playlist` — HLS playlist validation against real
//! committed `.m3u8` files.
//!
//! Fixtures live in `fixtures/hls/`:
//! - `valid.m3u8` — well-formed playlist → zero findings.
//! - `missing-extm3u.m3u8` — missing `#EXTM3U` header.
//! - `bad-extinf.m3u8` — EXTINF 15.0 vs TARGETDURATION 10.
//! - `malformed-daterange.m3u8` — DATERANGE missing required `ID` attribute.
//! - `reference-vod.m3u8` — 10-segment VOD playlist generated by
//!   `broadcast_hls::MediaPlaylist::to_m3u8()`.

use std::fs;

use media_doctor::{Report, check_playlist};

fn read_fixture(name: &str) -> String {
    let path = format!("{}/../fixtures/hls/{}", env!("CARGO_MANIFEST_DIR"), name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read fixture {path}: {e}"))
}

fn findings<'a>(report: &'a Report, rule_id: &str) -> Vec<&'a media_doctor::Finding> {
    report
        .findings()
        .iter()
        .filter(|f| f.rule_id == rule_id)
        .collect()
}

/// `valid.m3u8` — well-formed playlist: #EXTM3U header, TARGETDURATION, EXTINF
/// durations ≤ target, valid DATERANGE. Expect ZERO findings.
#[test]
fn valid_fixture() {
    let text = read_fixture("valid.m3u8");
    let mut report = Report::new();
    check_playlist(&text, &mut report);

    assert!(
        report.is_empty(),
        "valid playlist should produce no findings, got {}: {:?}",
        report.len(),
        report.findings(),
    );
}

/// `missing-extm3u.m3u8` — first non-empty line is `#EXT-X-VERSION:3` instead of
/// `#EXTM3U`. Expect at least one `hls-missing-extm3u` finding.
#[test]
fn missing_extm3u_fixture() {
    let text = read_fixture("missing-extm3u.m3u8");
    let mut report = Report::new();
    check_playlist(&text, &mut report);

    let extm3u = findings(&report, "hls-missing-extm3u");
    assert!(
        !extm3u.is_empty(),
        "missing-extm3u fixture should produce hls-missing-extm3u finding(s), got {}: {:?}",
        extm3u.len(),
        report.findings(),
    );
}

/// `bad-extinf.m3u8` — EXTINF 15.0 vs TARGETDURATION 10 (15 rounded = 15 > 10).
/// Expect at least one `hls-extinf-exceeds-target` finding.
#[test]
fn bad_extinf_fixture() {
    let text = read_fixture("bad-extinf.m3u8");
    let mut report = Report::new();
    check_playlist(&text, &mut report);

    let exceeds = findings(&report, "hls-extinf-exceeds-target");
    assert!(
        !exceeds.is_empty(),
        "bad-extinf fixture should produce hls-extinf-exceeds-target finding(s), got {}: {:?}",
        exceeds.len(),
        report.findings(),
    );
}

/// `malformed-daterange.m3u8` — DATERANGE line missing required `ID` attribute.
/// Expect at least one `hls-malformed-daterange` finding.
#[test]
fn malformed_daterange_fixture() {
    let text = read_fixture("malformed-daterange.m3u8");
    let mut report = Report::new();
    check_playlist(&text, &mut report);

    let dr = findings(&report, "hls-malformed-daterange");
    assert!(
        !dr.is_empty(),
        "malformed-daterange fixture should produce hls-malformed-daterange finding(s), got {}: {:?}",
        dr.len(),
        report.findings(),
    );
}

/// `reference-vod.m3u8` — a real VOD media playlist generated by this
/// workspace's own `broadcast_hls::MediaPlaylist::to_m3u8()` (10 segments, 10s
/// TARGETDURATION, ENDLIST). It is NOT hand-made bytes; the same struct
/// shape is exercised by `broadcast-hls/tests/hls_playlist.rs`. Must produce
/// zero findings.
#[test]
fn reference_vod_playlist_clean() {
    let text = read_fixture("reference-vod.m3u8");
    let mut report = Report::new();
    check_playlist(&text, &mut report);
    assert!(
        report.is_empty(),
        "reference VOD playlist should have no findings, got {}: {:?}",
        report.len(),
        report.findings(),
    );
}

// -------------------------------------------------------------------------
// Audit MD-W10: one implementation, not two
// -------------------------------------------------------------------------

/// The four rules whose messages had **drifted** between the old duplicate
/// `playlist.rs` and `hls_validator.rs` must now be emitted by the single
/// implementation with its clause citation intact.
///
/// The old `playlist.rs` messages, recovered from git history:
///
/// ```text
/// First non-empty line must be exactly '#EXTM3U'
/// Media playlist with EXTINF entries must include #EXT-X-TARGETDURATION
/// EXTINF duration {dur} (rounded to {rounded}) exceeds TARGETDURATION {targetduration_val}
/// Malformed #EXT-X-DATERANGE line
/// ```
///
/// None named the RFC clause; the surviving implementation's do. A test that
/// merely compared `check_playlist` with `check_hls_playlist` would be a
/// tautology now that the former calls the latter — this pins the actual
/// behaviour each rule produces instead.
#[test]
fn drifted_rules_now_carry_their_clause_citation() {
    // hls-missing-extm3u — §4.4.1.1
    let text = "not-a-playlist\n".to_string();
    let mut report = Report::new();
    check_playlist(&text, &mut report);
    let hit = findings(&report, "hls-missing-extm3u");
    assert_eq!(hit.len(), 1, "got {:?}", report.findings());
    assert!(
        hit[0].message.contains("§4.4.1.1"),
        "the message must cite the clause, got {:?}",
        hit[0].message,
    );

    // hls-missing-targetduration — §4.4.3.1
    let text = "#EXTM3U\n#EXTINF:1.0,\nseg.ts\n".to_string();
    let mut report = Report::new();
    check_playlist(&text, &mut report);
    let hit = findings(&report, "hls-missing-targetduration");
    assert_eq!(hit.len(), 1, "got {:?}", report.findings());
    assert!(
        hit[0].message.contains("§4.4.3.1"),
        "the message must cite the clause, got {:?}",
        hit[0].message,
    );

    // hls-extinf-exceeds-target — §4.4.3.1
    let text = "#EXTM3U\n#EXT-X-TARGETDURATION:4\n#EXTINF:9.0,\nseg.ts\n".to_string();
    let mut report = Report::new();
    check_playlist(&text, &mut report);
    let hit = findings(&report, "hls-extinf-exceeds-target");
    assert_eq!(hit.len(), 1, "got {:?}", report.findings());
    assert!(
        hit[0].message.contains("§4.4.3.1"),
        "the message must cite the clause, got {:?}",
        hit[0].message,
    );

    // hls-malformed-daterange — §4.4.5.1. A DATERANGE without the required
    // ID attribute (§4.4.5.1: ID is REQUIRED).
    let text = "#EXTM3U\n#EXT-X-DATERANGE:START-DATE=\"2020-01-01T00:00:00Z\"\n".to_string();
    let mut report = Report::new();
    check_playlist(&text, &mut report);
    let hit = findings(&report, "hls-malformed-daterange");
    assert_eq!(hit.len(), 1, "got {:?}", report.findings());
    assert!(
        hit[0].message.contains("§4.4.5.1"),
        "the message must cite the clause, got {:?}",
        hit[0].message,
    );
}
