//! Fixture tests for `check_hls_playlist` — HLS playlist validation using
//! structured model (broadcast_hls::MediaPlaylist::parse) plus line-based checks.
//!
//! Fixtures live in `fixtures/hls/`:
//! - `valid.m3u8` — well-formed playlist → zero findings.
//! - `missing-extm3u.m3u8` — missing `#EXTM3U` header.
//! - `bad-extinf.m3u8` — EXTINF 15.0 vs TARGETDURATION 10.
//! - `malformed-daterange.m3u8` — DATERANGE missing required `ID` attribute.
//! - `reference-vod.m3u8` — 10-segment VOD playlist generated by broadcast_hls::MediaPlaylist::to_m3u8().

use std::fs;

use media_doctor::{Report, check_hls_playlist};

fn read_fixture(name: &str) -> String {
    let path = format!("{}/../fixtures/hls/{}", env!("CARGO_MANIFEST_DIR"), name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read fixture {path}: {e}"))
}

fn findings<'a>(report: &'a Report, rule_id: &str) -> Vec<&'a media_doctor::Finding> {
    report
        .findings()
        .iter()
        .filter(|f| f.rule_id == rule_id)
        .collect()
}

// -------------------------------------------------------------------------
// Clean manifest — zero findings
// -------------------------------------------------------------------------

/// `valid.m3u8` — well-formed media playlist → ZERO findings.
#[test]
fn valid_fixture_clean() {
    let text = read_fixture("valid.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);

    assert!(
        report.is_empty(),
        "valid playlist should produce no findings, got {}: {:?}",
        report.len(),
        report.findings(),
    );
}

/// `reference-vod.m3u8` — a real VOD playlist generated by this workspace's
/// own `broadcast_hls::MediaPlaylist::to_m3u8()` (10 segments, 10s TARGETDURATION,
/// ENDLIST). Must produce zero findings.
#[test]
fn reference_vod_playlist_clean() {
    let text = read_fixture("reference-vod.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);
    assert!(
        report.is_empty(),
        "reference VOD playlist should have no findings, got {}: {:?}",
        report.len(),
        report.findings(),
    );
}

// -------------------------------------------------------------------------
// Positive tests — violations are detected
// -------------------------------------------------------------------------

/// Missing `#EXTM3U` header → `hls-missing-extm3u` finding.
#[test]
fn missing_extm3u_detected() {
    let text = read_fixture("missing-extm3u.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);

    let hits = findings(&report, "hls-missing-extm3u");
    assert!(
        !hits.is_empty(),
        "missing-extm3u fixture should produce hls-missing-extm3u, got {:?}",
        report.findings(),
    );
}

/// EXTINF 15.0 > TARGETDURATION 10 → `hls-extinf-exceeds-target` finding.
#[test]
fn extinf_exceeds_target_detected() {
    let text = read_fixture("bad-extinf.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);

    let hits = findings(&report, "hls-extinf-exceeds-target");
    assert!(
        !hits.is_empty(),
        "bad-extinf should produce hls-extinf-exceeds-target, got {:?}",
        report.findings(),
    );
}

/// Malformed DATERANGE → `hls-malformed-daterange` finding.
#[test]
fn malformed_daterange_detected() {
    let text = read_fixture("malformed-daterange.m3u8");
    let mut report = Report::new();
    check_hls_playlist(&text, &mut report);

    let hits = findings(&report, "hls-malformed-daterange");
    assert!(
        !hits.is_empty(),
        "malformed-daterange should produce hls-malformed-daterange, got {:?}",
        report.findings(),
    );
}

// -------------------------------------------------------------------------
// LL-HLS structured-model tests
// -------------------------------------------------------------------------

/// A playlist with both ENDLIST and PRELOAD-HINT → `hls-preload-hint-with-endlist`.
#[test]
fn preload_hint_with_endlist_detected() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PRELOAD-HINT:TYPE=PART,URI=\"next-part.m4s\"
#EXTINF:4.0,
seg0.m4s
#EXT-X-ENDLIST
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-preload-hint-with-endlist");
    assert!(
        !hits.is_empty(),
        "preload-hint+endlist should produce finding, got {:?}",
        report.findings(),
    );
}

/// A playlist with EXT-X-SKIP but no CAN-SKIP-UNTIL → `hls-skip-without-can-skip-until`.
#[test]
fn skip_without_can_skip_until_detected() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:100
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-SKIP:SKIPPED-SEGMENTS=96
#EXTINF:4.0,
seg100.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-skip-without-can-skip-until");
    assert!(
        !hits.is_empty(),
        "skip without CAN-SKIP-UNTIL should produce finding, got {:?}",
        report.findings(),
    );
}

/// A playlist with a part whose duration is below 85% of PART-TARGET.
#[test]
fn part_duration_too_short_detected() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        !hits.is_empty(),
        "too-short part duration should produce finding, got {:?}",
        report.findings(),
    );
    assert!(
        hits.iter()
            .any(|f| f.severity == media_doctor::Severity::Error),
        "too-short part duration must be Error severity, not Warning"
    );
}

/// A part below 85% duration floor with `INDEPENDENT=YES` is ACCEPTED
/// (RFC 8216bis §4.4.4.9 exception).
#[test]
fn short_part_with_independent_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\",INDEPENDENT=YES
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        hits.is_empty(),
        "INDEPENDENT=YES part below 85% floor must be accepted, got {:?}",
        report.findings(),
    );
}

/// A part below 85% duration floor with `GAP=YES` is ACCEPTED
/// (RFC 8216bis §4.4.4.9 exception).
#[test]
fn short_part_with_gap_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\",GAP=YES
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        hits.is_empty(),
        "GAP=YES part below 85% floor must be accepted, got {:?}",
        report.findings(),
    );
}

/// A part below 85% duration floor IMMEDIATELY BEFORE a `GAP=YES` part is
/// ACCEPTED (RFC 8216bis §4.4.4.9 exception).
#[test]
fn short_part_before_gap_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.100,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.333,URI=\"part1.m4s\",GAP=YES
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        hits.is_empty(),
        "part before GAP=YES below 85% floor must be accepted, got {:?}",
        report.findings(),
    );
}

/// The FINAL part of a segment below 85% duration floor is ACCEPTED
/// (RFC 8216bis §4.4.4.9 exception).
#[test]
fn short_final_part_of_segment_accepted() {
    let text = "\
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.0
#EXT-X-PART-INF:PART-TARGET=0.333
#EXT-X-PART:DURATION=0.333,URI=\"part0.m4s\"
#EXT-X-PART:DURATION=0.100,URI=\"part1.m4s\"
#EXTINF:1.0,
seg0.m4s
";
    let mut report = Report::new();
    check_hls_playlist(text, &mut report);

    let hits = findings(&report, "hls-part-duration-range");
    assert!(
        hits.is_empty(),
        "final part of segment below 85% floor must be accepted, got {:?}",
        report.findings(),
    );
}
