//! Real-fixture, independent-oracle proof for issue #1052 (r01-C1):
//! `PES_extension_field_length` is `marker_bit(1) + PES_extension_field_length(7)`
//! (ISO/IEC 13818-1 §2.4.3.7, Table 2-21), not a plain 8-bit length. The pre-fix
//! parser read the whole byte as the length, so any real
//! `PES_extension_flag_2 == 1` packet — every `stream_id == 0xFD`
//! ("extended_stream_id") PES in practice — was rejected with
//! `BufferTooShort`.
//!
//! ## Fixture: `dirac-vc2-extended-stream-id.ts`
//! `ffmpeg 8.1.2`'s `vc2` (SMPTE VC-2 / Dirac) encoder, one of the few codecs
//! ffmpeg muxes into MPEG-TS with `stream_id` `0xFD`, from synthetic
//! `lavfi`/`color` input (`-f lavfi -i "color=c=black:size=32x32:rate=5:
//! duration=0.4" -c:v vc2 -b:v 50k -f mpegts`). Only the video PID's TS packets
//! are kept (PAT/PMT stripped) — see `fixtures/PROVENANCE.md`.
//!
//! Expected values below (`PES_extension_field_length` = 1,
//! `stream_id_extension_flag` = 0, `stream_id_extension` = `0x60`) are read
//! directly off the muxed bytes (independent of this crate's own parser/
//! serializer): the optional-header region is `21 00 07 d8 61` (5-byte
//! PTS-only) then `01 81 60` (the `PesExtension`: flags byte `0x01` =
//! `PES_extension_flag_2` only, then `0x81` = `marker_bit(1)=1` +
//! `PES_extension_field_length(7)=1`, then the single
//! `stream_id_extension` byte `0x60` = flag `0` + low bits `0x60`).

use mpeg_pes::{PesAssembler, PesPacket, StreamId};
use std::fs;

fn fixture_bytes() -> Vec<u8> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../fixtures/mpeg-pes/dirac-vc2-extended-stream-id.ts"
    );
    fs::read(path).expect("fixture dirac-vc2-extended-stream-id.ts must be present")
}

const PKT: usize = 188;

/// (pid, payload_unit_start, payload) for a TS packet, handling both
/// payload-only and adaptation-field+payload packets.
fn ts_payload(p: &[u8]) -> Option<(u16, bool, &[u8])> {
    if p.len() != PKT || p[0] != 0x47 {
        return None;
    }
    let pid = (u16::from(p[1] & 0x1F) << 8) | u16::from(p[2]);
    let pusi = p[1] & 0x40 != 0;
    let afc = (p[3] >> 4) & 0x03;
    let start = match afc {
        1 => 4,
        3 => 5 + usize::from(p[4]),
        _ => return None,
    };
    if start > PKT {
        return None;
    }
    Some((pid, pusi, &p[start..PKT]))
}

fn extract_pes_packets() -> Vec<Vec<u8>> {
    let ts = fixture_bytes();
    assert_eq!(ts.len() % PKT, 0);
    let mut asm = PesAssembler::new();
    let mut out = Vec::new();
    for pkt in ts.chunks(PKT) {
        if let Some((_pid, pusi, payload)) = ts_payload(pkt)
            && let Some(v) = asm.feed(pusi, payload)
        {
            out.push(v);
        }
    }
    if let Some(v) = asm.flush() {
        out.push(v);
    }
    out
}

/// The pre-fix parser rejected every one of these packets with
/// `BufferTooShort` (it read the whole `0x81` byte as a 129-byte
/// `PES_extension_field_length`, when only 1 byte of optional-header space
/// remained). Confirms the fixture is exactly the case #1052 describes and
/// that it now parses cleanly.
#[test]
fn extended_stream_id_pes_parses_and_extension_field_is_typed() {
    let packets = extract_pes_packets();
    assert!(
        packets.len() >= 2,
        "expected >=2 PES packets, got {}",
        packets.len()
    );

    for (i, raw) in packets.iter().enumerate() {
        let pes = PesPacket::parse(raw).unwrap_or_else(|e| {
            panic!("pkt {i}: PES_extension_flag_2 packet must parse, got {e:?}")
        });
        assert_eq!(pes.stream_id, StreamId(0xFD), "pkt {i}: extended_stream_id");

        let header = pes
            .header
            .as_ref()
            .expect("pkt {i}: optional header present");
        let ext = header
            .pes_extension
            .as_ref()
            .expect("pkt {i}: PES_extension_flag must be set");
        let field = ext
            .pes_extension_field
            .as_ref()
            .expect("pkt {i}: PES_extension_flag_2 must be set");

        // Read directly off the independently-generated bytes (see module doc).
        assert!(
            !field.stream_id_extension_flag,
            "pkt {i}: stream_id_extension_flag must be 0"
        );
        assert_eq!(
            field.low_bits, 0x60,
            "pkt {i}: stream_id_extension must be 0x60"
        );
        assert!(
            field.rest.is_empty(),
            "pkt {i}: PES_extension_field_length is 1, nothing follows the \
             stream_id_extension byte"
        );
    }
}

/// Byte-identical round trip of the full PES packet, the workspace's hard
/// wire-codec invariant, over the real fixture bytes.
#[test]
fn extended_stream_id_pes_round_trips_byte_identical() {
    let packets = extract_pes_packets();
    for (i, raw) in packets.iter().enumerate() {
        let pes = PesPacket::parse(raw).expect("PES parses");
        let mut out = vec![0u8; pes.serialized_len()];
        let n = pes.serialize_into(&mut out).expect("serialize");
        assert_eq!(n, raw.len(), "pkt {i}: serialized length mismatch");
        assert_eq!(
            &out[..n],
            raw.as_slice(),
            "pkt {i}: NOT byte-identical\n  orig: {}\n  out:  {}",
            raw.iter().map(|b| format!("{b:02X}")).collect::<String>(),
            out[..n]
                .iter()
                .map(|b| format!("{b:02X}"))
                .collect::<String>(),
        );
    }
}
