//! Real MPEG-TS media through the adapter and a genuine libsrt, both
//! directions, judged by `ffprobe` (issue #1131's "independent oracle" for
//! the data path; the other interop tests move patterned bytes).
//!
//! A two-second audio+video transport stream is generated by `ffmpeg`, sent
//! over SRT in the live-mode 1316-byte (7 × 188) datagrams, and the stream
//! received on the far side must be byte-identical *and* `ffprobe` must
//! report the same streams with the same decoded frame counts for the input
//! and the output file.
//!
//! * `our_caller_to_libsrt_listener`: our [`SrtSocket`] sends to
//!   `srt-live-transmit srt://:PORT udp://..`.
//! * `libsrt_caller_to_our_listener`: `srt-live-transmit udp://:PORT srt://..`
//!   sends to our [`SrtListener`].
//!
//! Skips LOUDLY if `srt-live-transmit`, `ffmpeg` or `ffprobe` is missing (set
//! `SRT_REQUIRE_LIBSRT=1` to make that a failure).
//!
//! Pacing is by acknowledgement, not by sleeping: each window of chunks is
//! only followed by the next once the far side has delivered it, so neither a
//! kernel UDP buffer nor libsrt's not-yet-connected source can drop one.

#![cfg(feature = "tokio")]

use std::net::{SocketAddr, UdpSocket};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::time::Duration;

use srt_runtime::handshake_sm::HandshakeConfig;
use srt_runtime::io::{SrtListener, SrtSocket};
use tokio::net::UdpSocket as TokioUdpSocket;

include!("support/skip.rs");

const TEST_TIMEOUT: Duration = Duration::from_secs(90);
/// Live-mode SRT payload: seven 188-byte TS packets.
const CHUNK: usize = 7 * 188;
/// Chunks in flight before waiting for the far side to deliver them.
const WINDOW: usize = 16;
/// TSBPD latency used on both ends. Generous on purpose: in a loaded test run a
/// stalled process would miss the default 120 ms play window and Too-Late Packet
/// Drop would (correctly) discard a chunk, failing the "every byte arrives"
/// check for a reason unrelated to the data path.
const LATENCY_MS: u16 = 1_000;
/// First byte of a synchronisation datagram (a TS packet starts `0x47`).
const SYNC_MARKER: u8 = 0x00;

struct KillOnDrop(Child);

impl Drop for KillOnDrop {
    fn drop(&mut self) {
        let _ = self.0.kill();
        let _ = self.0.wait();
    }
}

fn spawn(cmd: &mut Command) -> KillOnDrop {
    KillOnDrop(
        cmd.stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("spawn srt-live-transmit"),
    )
}

fn free_udp_port() -> u16 {
    UdpSocket::bind("127.0.0.1:0")
        .expect("bind free port")
        .local_addr()
        .expect("local addr")
        .port()
}

fn work_dir(name: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(format!("libsrt_media_{name}"));
    std::fs::create_dir_all(&dir).expect("create work dir");
    dir
}

/// Generate the test stream with ffmpeg: MPEG-2 video + MP2 audio, 2 s.
fn make_ts(path: &Path) -> Vec<u8> {
    let status = Command::new("ffmpeg")
        .args(["-hide_banner", "-loglevel", "error", "-y"])
        .args([
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=2:size=320x240:rate=25",
        ])
        .args(["-f", "lavfi", "-i", "sine=duration=2"])
        .args([
            "-c:v",
            "mpeg2video",
            "-b:v",
            "800k",
            "-c:a",
            "mp2",
            "-shortest",
        ])
        .args(["-f", "mpegts"])
        .arg(path)
        .status()
        .expect("run ffmpeg");
    assert!(
        status.success(),
        "ffmpeg could not generate the test stream"
    );
    let ts = std::fs::read(path).expect("read generated ts");
    assert_eq!(ts.len() % 188, 0, "whole TS packets");
    assert!(ts.len() > CHUNK * WINDOW, "a meaningful stream");
    ts
}

/// `ffprobe` the stream codecs and decoded frame counts of `path`.
fn probe(path: &Path) -> String {
    let out = Command::new("ffprobe")
        .args(["-v", "error", "-count_frames"])
        .args(["-show_entries", "stream=codec_name,nb_read_frames"])
        .args(["-of", "csv=p=0"])
        .arg(path)
        .output()
        .expect("run ffprobe");
    assert!(
        out.status.success(),
        "ffprobe rejected {}: {}",
        path.display(),
        String::from_utf8_lossy(&out.stderr)
    );
    let summary = String::from_utf8(out.stdout).expect("utf8");
    assert!(
        summary.contains("mpeg2video") && summary.contains("mp2"),
        "ffprobe found no video+audio in {}: {summary:?}",
        path.display()
    );
    summary
}

fn assert_media_equal(input: &Path, output: &Path, original: &[u8], received: &[u8]) {
    assert_eq!(received.len(), original.len(), "received stream length");
    assert!(
        received == original,
        "received stream is not byte-identical"
    );
    std::fs::write(output, received).expect("write received ts");
    assert_eq!(
        probe(output),
        probe(input),
        "ffprobe disagrees about the received stream"
    );
}

/// Our caller → libsrt listener → UDP.
#[tokio::test]
async fn our_caller_to_libsrt_listener() {
    skip_unless_tools!("srt-live-transmit" => "-version", "ffmpeg" => "-version", "ffprobe" => "-version");
    tokio::time::timeout(TEST_TIMEOUT, async {
        let dir = work_dir("caller");
        let (input, output) = (dir.join("in.ts"), dir.join("out.ts"));
        let original = make_ts(&input);

        let listen_port = free_udp_port();
        let discard = TokioUdpSocket::bind("127.0.0.1:0").await.unwrap();
        let discard_port = discard.local_addr().unwrap().port();
        let _libsrt = spawn(
            Command::new("srt-live-transmit")
                .arg("-loglevel:error")
                .arg(format!("srt://:{listen_port}?latency={LATENCY_MS}"))
                .arg(format!("udp://127.0.0.1:{discard_port}")),
        );
        let mut caller = SrtSocket::connect(
            format!("127.0.0.1:{listen_port}")
                .parse::<SocketAddr>()
                .unwrap(),
            HandshakeConfig::default(),
        )
        .await
        .expect("connect to libsrt");

        let mut received = Vec::with_capacity(original.len());
        let mut buf = vec![0u8; 65536];
        for window in original.chunks(CHUNK * WINDOW) {
            let mut expected_chunks = 0;
            for chunk in window.chunks(CHUNK) {
                caller.send(chunk).await.expect("send");
                expected_chunks += 1;
            }
            for _ in 0..expected_chunks {
                let n = tokio::time::timeout(Duration::from_secs(15), discard.recv(&mut buf))
                    .await
                    .expect("libsrt did not forward a chunk")
                    .expect("recv");
                received.extend_from_slice(&buf[..n]);
            }
        }
        assert_media_equal(&input, &output, &original, &received);
    })
    .await
    .expect("test timed out");
}

/// libsrt caller (reading a UDP source) → our listener.
#[tokio::test]
async fn libsrt_caller_to_our_listener() {
    skip_unless_tools!("srt-live-transmit" => "-version", "ffmpeg" => "-version", "ffprobe" => "-version");
    tokio::time::timeout(TEST_TIMEOUT, async {
        let dir = work_dir("listener");
        let (input, output) = (dir.join("in.ts"), dir.join("out.ts"));
        let original = make_ts(&input);

        let mut listener = SrtListener::bind(
            "127.0.0.1:0".parse::<SocketAddr>().unwrap(),
            HandshakeConfig {
                latency_ms: LATENCY_MS,
                ..HandshakeConfig::default()
            },
        )
        .await
        .expect("bind");
        let bound = listener.local_addr().unwrap();
        let accept = tokio::spawn(async move { listener.accept().await.expect("accept") });
        let src_port = free_udp_port();
        let _libsrt = spawn(
            Command::new("srt-live-transmit")
                .arg("-loglevel:error")
                .arg(format!("-chunk:{CHUNK}"))
                .arg(format!("udp://:{src_port}"))
                .arg(format!(
                    "srt://127.0.0.1:{}?latency={LATENCY_MS}",
                    bound.port()
                )),
        );
        let mut receiver = tokio::time::timeout(Duration::from_secs(10), accept)
            .await
            .expect("accept timed out")
            .expect("join");

        let feed = TokioUdpSocket::bind("127.0.0.1:0").await.unwrap();
        let target = ("127.0.0.1", src_port);

        // libsrt drops what its UDP source sees until its SRT side has
        // connected: send a marked sync datagram until one comes out.
        let mut ticker = tokio::time::interval(Duration::from_millis(50));
        loop {
            tokio::select! {
                _ = ticker.tick() => {
                    feed.send_to(&[SYNC_MARKER; 64], target).await.unwrap();
                }
                r = receiver.recv() => {
                    let payload = r.expect("recv").expect("connection ended");
                    if payload.first() == Some(&SYNC_MARKER) {
                        break;
                    }
                }
            }
        }

        let mut received = Vec::with_capacity(original.len());
        for window in original.chunks(CHUNK * WINDOW) {
            let mut expected_chunks = 0;
            for chunk in window.chunks(CHUNK) {
                feed.send_to(chunk, target).await.unwrap();
                expected_chunks += 1;
            }
            let mut got = 0;
            while got < expected_chunks {
                let payload = tokio::time::timeout(Duration::from_secs(15), receiver.recv())
                    .await
                    .expect("our listener did not deliver a chunk")
                    .expect("recv")
                    .expect("connection ended");
                if payload.first() == Some(&SYNC_MARKER) {
                    continue; // a late sync datagram
                }
                received.extend_from_slice(&payload);
                got += 1;
            }
        }
        assert_media_equal(&input, &output, &original, &received);
    })
    .await
    .expect("test timed out");
}
